baseURL = "https://subhrajyoti.me"
languageCode = "en-us"
title = "Subhrajyoti Sen"
theme = "typo"
googleAnalytics = "G-YW5C4D2DZ7"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Subhrajyoti Sen"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a Software Engineer with a strong foundation in computer science and a passion for solving complex problems.
I am interested in a range of topics, including mobile apps, operating systems and public policy.
"""

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "twitter"
url  = "https://twitter.com/iamsubhrajyoti"

[[params.social]]
name = "github"
url  = "https://github.com/SubhrajyotiSen"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/subhrajyotisen/"

# Main menu pages
[[params.menu]]
    name       = "About"
    url        = "/about"
[[params.menu]]
    name       = "Blog"
    url        = "/posts"
[[params.menu]]
    name       = "Public-Speaking"
    url        = "/public-speaking"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
