[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.152.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.152.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.152.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.152.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; script-src 'self' www.googletagmanager.com www.google-analytics.com 'unsafe-inline';"

[[redirects]]
  from = "/countries"
  to = "/countries/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/countries/"
  to = "/countries/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/countries/index.html"
  to = "https://visited-countries-subh.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/countries/*"
  to = "https://visited-countries-subh.netlify.app/:splat"
  status = 200
  force = true
